#!/bin/bash

set -e

minorVer="1.20.2"

# Parse image name for repo name, and define major tag
tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}
majorVer=${minorVer:0:4}

# Tag and push image with <minor>
echo "Tagging and pushing ${repoName}:${minorVer} ..."
docker tag "$IMAGE_NAME" "${repoName}:${minorVer}"
docker push "${repoName}:${minorVer}"

# Tag and push image with <major>
echo "Tagging and pushing ${repoName}:${majorVer} ..."
docker tag "$IMAGE_NAME" "${repoName}:${majorVer}"
docker push "${repoName}:${majorVer}"
